### ISSUE TITLE
picam activation

### ISSUE THREAD

**Issue by akod1ng** [steve-vincent/SentryTurret#2]
Hi,
First: Thanks for sharing this project.
Second: I have a problem with adding the camera as described:

> > Camera: For using raspicam with opencv, add bcm2835-v4l2 to /etc/modules (more).

I can access the camera via terminal but dont know what to do with this part: add bcm2835-v4l2 to /etc/modules
Can you elaborate on this? 

Thanks,
andi

**Comment by decentropy** [comment]
I linked some articles I read which helped me on the readme:
https://www.raspberrypi.org/forums/viewtopic.php?t=62364
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=94381

Reviewing those links... it think all I did to load the module in Linux is:
$ sudo modprobe bcm2835-v4l2

You may need to install these packages as well (for the picam)
$ sudo apt-get install uv4l uv4l-raspicam

The setup above is simply letting you use the picam with opencv.
You can run some simple python opencv script to test that works. (perhaps something like this: https://gist.github.com/tedmiston/6060034 )
